export const MyProjects = [
  { ProjectID: 0, ProjectName: "List-Of-Bastards", ProjectSheetID: "1D7Sspk-FK558EvcTQsIfc5dwccoaggvRtrEPUlswNOU" },
  { ProjectID: 1, ProjectName: "Vardon", ProjectSheetID: "10FmrdvAHb6K2ogYFxUO2pLWfs5lr44c5PXTFyaUHNgE" },
  { ProjectID: 2, ProjectName: "Sanctnary", ProjectSheetID: "1IWSBaeZw54l7CE-sJ3eEyP5Cximia1YOsycOjG53IVg" },

  { ProjectID: 4, ProjectName: "Amazonia", ProjectSheetID: "1hN1zoTKVk0S3sMYg-tubMs2WHIdtDCI7AjkNvIFmotM" },
  { ProjectID: 5, ProjectName: "Pacifica", ProjectSheetID: "1UeuC8fzjsy7Xfsc8syhcxEYUxsTzTbP1vXrDoGm8MOw" },
  { ProjectID: 6, ProjectName: "Acuna", ProjectSheetID: "1ZGIGDwEjXg6DvMF_VG7ELoO6ieDirbrdboZukQFQnOg" },
  { ProjectID: 7, ProjectName: "Centaury", ProjectSheetID: "14IlE5teKGmtC1EdGj3yNmSEruRSk7aU24DezRUJezD4" },
  { ProjectID: 8, ProjectName: "Trixis", ProjectSheetID: "1k8ODkRAZzEKSNA4GdF8pYoBMsH1tNneyokpLX99sop4" },
  { ProjectID: 9, ProjectName: "Janusia", ProjectSheetID: "1p0Fngwst3BEv1gl40J02o08jDcVETs67zFUv-wTED9s" },
  { ProjectID: 10, ProjectName: "Sycamore", ProjectSheetID: "1fx_Yb2UvnvLGA1SUHZ9rYz20ewYC5LSnIoBNp6i03gc" },
  { ProjectID: 12, ProjectName: "Aquilegia", ProjectSheetID: "1f_4mcSt7EyatDA0499QcWF5KWsfvLNbeRMfi797OfUw" },
  { ProjectID: 13, ProjectName: "Zinnia", ProjectSheetID: "1Q6O4yT8tW7XXZTdcnywcOId-FWFi55sQ_bLS_YO3Cg8" },
  { ProjectID: 14, ProjectName: "Claret", ProjectSheetID: "12wBWbtRlytw_ndv_sWBoDFbCBKL3wWJBpBUGp7EvXb4" },
  { ProjectID: 15, ProjectName: "Juniper", ProjectSheetID: "1B4nU5ecOF_0nI2juO7zSTb_aXqnbhEvJ8uBKnFXJlKQ" },
  // {ProjectID:16, ProjectName:"", ProjectSheetID:""},
  { ProjectID: 17, ProjectName: "Primrose", ProjectSheetID: "1WZaP0Yf3qsS0l_S-CHDq3Cda96LOkmfjOjKT2_8SO1Q" },
  // {ProjectID:19, ProjectName:"", ProjectSheetID:""},
  // {ProjectID:20, ProjectName:"Aster", ProjectSheetID:""},
  // {ProjectID:21, ProjectName:"Coursetia", ProjectSheetID:"1b3arjg1xbR2LFWJeQJYphdSQdl9wcA8Mt5j8GtRqEDA"},
  { ProjectID: 25, ProjectName: "Basswood", ProjectSheetID: "1KPk0z_pV7gbXyvpD02JpEV-PwJ-2CEs4B86dG1-L7IY" },
  { ProjectID: 26, ProjectName: "Victoria", ProjectSheetID: "1oq1bVLLUNOXrBPYA6s9QewklQMgZE20kiTgkLThOyZE" },
  { ProjectID: 30, ProjectName: "Albizia", ProjectSheetID: "112ioVt8wlUF79G_MEKXTTG9yiD42YAJ5SHKFlf67hHI" },
  { ProjectID: 27, ProjectName: "Mimosa", ProjectSheetID: "1eM15xDiF9Kb4SAW4Mq4CYPa7RYWZzP8G3S2hOnd_i3E" },
  { ProjectID: 29, ProjectName: "Avencia-2", ProjectSheetID: "1s5gwvLRsEgvxtfoLXHs2O3EqyU48k49e8wv0AY_j31E" },
  { ProjectID: 32, ProjectName: "Amargo", ProjectSheetID: "1S53U2WMP0SmbnGIeUhYJ9f3q6iumgXyqicHr0f80Zrw" },
  { ProjectID: 33, ProjectName: "Oxygen2023", ProjectSheetID: "1wBX2zhUaBg082BUmGCvqCSPI6w8eDJFtxZAsH2LjiaY" },
  { ProjectID: 34, ProjectName: "Viridis", ProjectSheetID: "1lY1q4tuzjeNGoTCfO55U7SytB-mwNSWzKw33VmXI23U" },
  { ProjectID: 35, ProjectName: "TAG2024", ProjectSheetID: "1Bw-5cJ9sPs__Yd2tdgRGPiWPriYN3PcCWpdAU-P_Vw0" },
  { ProjectID: 36, ProjectName: "SYC-ZIN-ODR", ProjectSheetID: "1QnTHakbfV6tAJFyptOFLT6l-YKhFIS8oTivkMr-qUgU" },
  { ProjectID: 37, ProjectName: "SidraOne2022", ProjectSheetID: "1e2rkpZzARq02EyNXIvgTfv6iHnff3Cc5lkBZ3uXgNxE" },
  { ProjectID: 38, ProjectName: "Aster-Coursetia", ProjectSheetID: "1n6XE3MOl0ATlpoSs3WNxNkISRGpS_3Cn7lL7LtWMqTI" },
  { ProjectID: 39, ProjectName: "TS2024", ProjectSheetID: "13gKEcFwa1urRbkXFZXNrj9bm2456U1YReEXH7CnYg8s" },
  { ProjectID: 40, ProjectName: "Navitas", ProjectSheetID: "1KpSykxgipRBnKRGH4tGDFspYhB2jwba_uLL9VMAEJe8" },
  { ProjectID: 41, ProjectName: "CLR-JNP-PMR", ProjectSheetID: "1etXIEtDxMNTDBH4UN5ZyEDEEuDNNEVPpmRVCsB1VgSk" },
  { ProjectID: 42, ProjectName: "D2-Attack-1", ProjectSheetID: "11lohD2eksc-SuCmTr6ZQeKGGqmITCafqxr6-JTBF8ug" },
  { ProjectID: 43, ProjectName: "D2-Attack-6bed", ProjectSheetID: "12Rto7K3xDrOmT_XLYdiBJszfQQAAwG0kFYFDYFXmF_s" },
  { ProjectID: 44, ProjectName: "Messages-Master-Bot", ProjectSheetID: "1ExnhMqBwN4KWaGdkizRkW20uyxk9Z4H1X0OlethBI-8" },
  { ProjectID: 45, ProjectName: "Lion-WorkSheet", ProjectSheetID: "1jHPMxc9EiJoI8_V_uaO23LkdkWW2-kiKKvG57qG0XpI" },
  { ProjectID: 46, ProjectName: "Sanctnary Unique", ProjectSheetID: "1XZvL6ggvxTjiO9EgUc-PR3NF_FzyNEsjV7VmlqYarYI" },
  { ProjectID: 47, ProjectName: "D22024NOV", ProjectSheetID: "1xPoYuU32UU8zb-qz37HqMi_5nQStzDTg1E4Y4wlaHjg" },
  { ProjectID: 48, ProjectName: "Lagoons", ProjectSheetID: "1h-6MlJIIy7GKN6QPP5mA9gtdAZ6Npw23v2IWB109E6E" },
  { ProjectID: 49, ProjectName: "Lagoons2024", ProjectSheetID: "1wMGXOYed6tRACBCIsjTqBiRbQfaGkkTIKigxgUdiD3A" },





];